repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [ pyproject-flake8 ]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.4
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: unittests
        name: run unit tests
        entry: cd src && python manage.py test
        language: system
        pass_filenames: false
        args: [ "discover" ]